#+title:     Ectorepo: Data Forensics
#+author:    David Conner
#+email:     noreply@te.xel.io


* Tsurugi

This info is copied from my personal notes, but originally from from SIFT videos
and other docs.

** A List of Useful Commands in Linux

*** LS Star

+ lspci :: list PCI things
+ lsusb :: list USB things
+ lsblk :: list block device things
+ lsscsi :: list SCSI things
+ lsof :: list open file things
+ lshw :: list hardware things
+ lsattr :: list file attributes on a Linux second extended file system
+ chattr :: "cut the chatter. in the byeee... bye bye bye."

*** Linux

+ dmesg :: examine or control the kernel ring buffer
+ free :: display amount of free and used memory in the system

*** Physical Layer Utils

+ hdparm :: get/set SATA/IDE device parameters
+ dd :: "convert and copy a file" but usually used to read/write to/from devices
  directly.
+ dc3dd :: patched version of the GNU =dd= tool
+ dcfldd :: an older fork of =dd= (a bit buggy as of 2016)

*** Media Management Layer Utils

+ ddrescue ::
+ fdisk :: manipulate fdisk partition table
+ gdisk :: interactive GUID partition table (GPT) manipulator

*** Super Shasum Tools For Hashing

+ md5 :: for MD5 hashes
+ sha(.*)sum :: for SHA checksums

*** Input Processing/Filtering

+ file :: determine file type
+ split :: split a file into pieces
+ cat :: concatenate files and print on the standard output
+ tac :: concat and print files in reverse
+ xxd :: creates a hex dump of a given file or standard input
+ tee :: for sporking things unless you'd like to foon them
+ wc :: print newline, word, and byte counts for each file
+ uniq :: this tool is a very special snowflake
+ tr :: translate, squeeze, and/or delete characters from standard input,
  writing to standard output.
+ df :: report file system disk space usage

*** Misc

+ bc :: an arbitrary precision calculator language for shell script calculations

*** EWF Format

On arch, install with =pacman -Syu libewf=

+

** SIFT Tools on Tsurugi Linux

|-------------------+--------------+-------------+-------------+----------+---------------|
| System : Layer -> | Physical     | Media Mgmnt | File System | File     | App           |
|-------------------+--------------+-------------+-------------+----------+---------------|
| Standard Tools    | lshw         | fdisk       | file        | file     | less/cat/grep |
|                   | lssci        | gdisk       | fsstat      | find     | xv regfmount  |
|                   | hdparm       | file -s     | fls         | ls & etc | display       |
|                   |              | mmls        |             |          |               |
|                   |              | mkfs        |             |          |               |
|-------------------+--------------+-------------+-------------+----------+---------------|
| SIFT/Autopsy/TSK  | tsk_recover  | mmls        | fsstat      | fls      | srch_strings  |
|                   | tsk_gettimes | mmcat       | icat        | fstat    |               |
|                   | sorter       | mmstat      | ils         | fcat     |               |
|                   | img_cat      |             | ifind       | hfind    |               |
|                   | img_stat     |             | istat       |          |               |
|                   | mactime      |             | blkcalc     |          |               |
|                   | sigfind      |             | blkcat      |          |               |
|                   |              |             | blkls       |          |               |
|                   |              |             | blkstat     |          |               |
|                   |              |             | jcat        |          |               |
|                   |              |             | jls         |          |               |
|-------------------+--------------+-------------+-------------+----------+---------------|

* Why now?
** Or "pretty much the worst security/tech advice ever"

My laptop suspiciously crashed yesterday. I was watching a stream when my laptop
just blackscreened with the fans on. It was not thermal, but I did touch the
laptop, so it's conceivable that I knocked a TB or USB connection loose and it
just so happened to cause linux/firmware to protectively crash -- power & device
management on Apple hardware does that to protect against rogue coulombs and
large vibrations ... which admittedly needs a swift factcheck ... punny, eh?

Regardless, what happened next was strange: my laptop was just blackscreened and
repeatedly trying to hold the power button resulted in no change -- i.e. it
wouldn't turn off so who knows what TF that is.

Instantly, as one does in situations like these before details like the
[[https://en.wikipedia.org/wiki/S.M.A.R.T.]["smart" status]] have shaken out, I thinks to myself I think:

#+begin_example
Hmmmm... my other laptop HD failed the other week in quite similar circumstances
when an HD failure on that laptop prevented me from completing some work for
someone

-- i.e. it was functionally coupled to some goal/work ... but isn't everything
on your laptop(s)?.
#+end_example

So, I once watched a youtube video on UEFI boots called [[https://www.youtube.com/watch?v=MRqfPmPaNgE&t=1239s][LinuxBoot: Firmware
Tools & a Busybox in Go!]]. It turns out that "Not All Operating Systems Go To
Heaven" because quite often they reincarnate as bits passed by various means
from the terminating OS program to the UEFI (and BIOS? ... factcheck, factcheck
in paragraph 3). What this means is that when a computer crashes in mysterious
circumstances and hardware/firmware seems to be immediately affected ... you
seem what I'm saying your bootloader/grub or whatever *could theoretically* be
hacked and you should not begin to load the OS per usual ... but you can't even
allow it to reach the OS.


Occam's Razor implies the most sophisticated attacks often have
the simplest vulnerabilities:

+ Stuck in a coffeeshop with a man in the middle?
  - Toggle Wifi/DHCP randomly to get a new IP.
  - Turn your wifi off.
  - Use AdGuard DNS ... for reasons.
+ Suspect a rogue Wifi?
  - Flick your wifi on real fast like a lightswitch and record the results with
    Wireshark running on an interface with an alternate MAC address.
+ Don't know what that service or process is?
  - Kill it. KILL THEM ALL ... just kidding. Don't do that.
  - No need to worry about their logging or dependent services.
  - Don't bother with googling, running in debug or using the system tools to
    inject profiling so you can examine things like: memory, performance
    baseline, nmap, open files/pipes ... yada yada yada. Just kill it.

All of those constitute terrible advice for circumstances you should avoid from
the beginning... but /goddamn/ hackers count on like 1,000 conditional
depenencies all to /break/ software in specific ways. If they can't leave a
trace, they have to make expectations/guarantees about the usage/state/design
norms in network/OS/software/hardware. If even a handful of those expectations
are violated, they risk leaving behind more identifiable traces of their entry
in logs and elsewhere. None of that is useful to the blue team unless they are
capable of analyzing specific deviations from norms or baseline while separating
it out from the noise that their own interference may have generated in the
logs.

#+begin_example
What I'm saying is that one should channel MacGuyver from that episode of
Stargate where they blow the replicators to pieces and Thor's all like "yeah!
that was so rad when the other aliens were all like pew pow, but you were slash,
crackpow bangbangbang!"

#+end_example

It's important to balance out that paranoia yes, but what paranoia
usually means is that you lack either awareness or mechanisms of control -- viz.
you just don't know what you don't know or couldn't your do anything about it if
your transferred object of fear/dread was actually like that.

Womp, womp.


After grub, it was dying fairly early in the Linux boot process because some
=/etc/fstab= drive mounts had exceeded their retries. Even in a livedisk, those
disks were unmountable.

I'm paranoid so I imaged them one at a time. Nothing was wrong with the =/root=
but I had gotten that one anyways. It turns out that TWO (not one) of my
partitions had significant errors from being.
